// frontend/layouts/default.tsx
import { Navbar } from "@/components/navbar";

export default function DefaultLayout({
  children,
  isLoggedIn,
}: {
  children: React.ReactNode;
  isLoggedIn: boolean;
}) {
  return (
    <div className="relative flex flex-col h-screen">
      <Navbar isLoggedIn={isLoggedIn} />
      <main className="container mx-auto max-w-7xl px-4 flex-grow pt-4">
        {children}
      </main>
      <footer className="w-full flex items-center justify-center py-3">
        <p>PeerPrep built by Group 47</p>
      </footer>
    </div>
  );
}

// frontend/Peerprep/layouts/default.vue
<template>
    <main class="h-screen w-full flex flex-col overflow-hidden">
        <Navbar v-if="showNavbar" />
        <div class="flex-grow overflow-y-auto">
            <slot />
        </div>
    </main>
</template>

<script setup>
import Navbar from '~/components/navigation/Navbar.vue';
</script>

<script>
export default {
    computed: {
        showNavbar() {
            const hiddenNavbarPaths = ['/users/login', '/users/register', '/collaboration'];

            return !hiddenNavbarPaths.includes(this.$route.path);
        }
    }
}
</script>
