// frontend/Peerprep/components/questions/EditQuestionDialog.vue
<script setup lang="ts">
import { ref, reactive, watch } from 'vue';
import type { Question } from '~/types/Question';
import { useToast } from '@/components/ui/toast/use-toast';

const props = defineProps<{
  question: Question;
  refreshData: () => void;
  isOpen: boolean;
}>();

const emit = defineEmits(['update:isOpen']);
const runtimeConfig = useRuntimeConfig();

const { toast } = useToast();

const editedQuestion = reactive({
  title: '',
  description: '',
  category: '',
  difficulty: 'easy',
});

const errors = reactive({
  title: false,
  description: false,
  category: false,
});

watch(() => props.isOpen, (newValue) => {
  if (newValue) {
    // Reset the form when the dialog opens
    editedQuestion.title = props.question.title;
    editedQuestion.description = props.question.description;
    editedQuestion.category = Array.isArray(props.question.category)
      ? props.question.category.join(', ')
      : props.question.category;
    editedQuestion.difficulty = props.question.difficulty;
  }
});

const validateForm = () => {
  let isValid = true;
  errors.title = !editedQuestion.title.trim();
  errors.description = !editedQuestion.description.trim();
  errors.category = !editedQuestion.category.trim();

  if (errors.title || errors.description || errors.category) {
    isValid = false;
  }

  return isValid;
};

const updateQuestion = async () => {
  if (!validateForm()) {
    toast({
      title: "Validation Error",
      description: "Please fill in all required fields.",
      variant: "destructive",
    });
    return;
  }

  try {
    const category_arr = editedQuestion.category.split(',').map(cat => cat.trim());

    const { data, error } = await useFetch(`${runtimeConfig.public.questionService}/questions/${props.question.id}`, {
      method: 'PUT',
      body: JSON.stringify({
        title: editedQuestion.title,
        description: editedQuestion.description,
        category: category_arr,
        difficulty: editedQuestion.difficulty
      }),
      headers: { 'Content-Type': 'application/json' }
    });

    if (error.value) {
      const errorMessage = await error.value?.data;
      toast({
        title: "Error updating question:",
        description: errorMessage.error,
        variant: "destructive",
      });
      console.error("Error updating question:", error.value);
    } else {
      console.log("Updated question successfully:", data.value);
      toast({
        title: "Success",
        description: "Question updated successfully",
      });
      props.refreshData();
      emit('update:isOpen', false); // Close the dialog only on successful update
    }
  } catch (err) {
    console.error("An error occurred while updating the question:", err);
  }
};
</script>

<template>
  <DialogContent class="sm:max-w-[525px]">
    <DialogHeader>
      <DialogTitle>Edit Question</DialogTitle>
      <DialogDescription>
        Update the details of the question
      </DialogDescription>
    </DialogHeader>
    <form @submit.prevent="updateQuestion" class="grid gap-5 py-4">
      <!-- Title -->
      <div class="grid grid-cols-4 items-center gap-4">
        <Label for="title">Title</Label>
        <div class="col-span-3">
          <Input id="title" v-model="editedQuestion.title" placeholder="Enter question title"
            :class="{ 'border-red-500': errors.title }" />
          <p v-if="errors.title" class="text-red-500 text-sm mt-1">Title is required</p>
        </div>
      </div>

      <div class="grid grid-cols-4 items-center gap-4">
        <Label for="description">Description</Label>
        <div class="col-span-3">
          <Textarea id="description" v-model="editedQuestion.description" placeholder="Enter question description"
            class="h-32" :class="{ 'border-red-500': errors.description }" />
          <p v-if="errors.description" class="text-red-500 text-sm mt-1">Description is required</p>
        </div>
      </div>

      <div class="grid grid-cols-4 items-center gap-4">
        <Label for="category">Category</Label>
        <div class="col-span-3">
          <Input id="category" v-model="editedQuestion.category" placeholder="Enter categories separated by commas"
            :class="{ 'border-red-500': errors.category }" />
          <p v-if="errors.category" class="text-red-500 text-sm mt-1">Category is required</p>
        </div>
      </div>

      <div class="grid grid-cols-4 items-center gap-4">
        <Label for="difficulty">Difficulty</Label>
        <Select id="difficulty" v-model="editedQuestion.difficulty">
          <SelectTrigger class="col-span-3">
            <SelectValue placeholder="Select a difficulty" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectItem value="easy">Easy</SelectItem>
              <SelectItem value="medium">Medium</SelectItem>
              <SelectItem value="hard">Hard</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
      </div>
      <Button type="submit" class="mt-4">
        Update
      </Button>
    </form>
  </DialogContent>
</template>

// frontend/src/components/questions/EditQuestionDialog.tsx
'use client'

import React from 'react'
import { Question, QuestionCategory, QuestionComplexity } from '@/types/question.types'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Label } from "@/components/ui/label"
import { MultiSelect } from "@/components/ui/multi-select"
import { Trash2 } from 'lucide-react'
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { questionSchema, QuestionFormData } from '../../types/forms/questionSchema'

interface EditQuestionDialogProps {
  question: Question | null
  isOpen: boolean
  onClose: () => void
  onSave: (question: Question) => void
  onDelete: () => void
}

export default function EditQuestionDialog({ question, isOpen, onClose, onSave, onDelete }: EditQuestionDialogProps) {
  const { control, handleSubmit, formState: { errors }, reset } = useForm<QuestionFormData>({
    resolver: zodResolver(questionSchema),
    defaultValues: question || {
      title: '',
      description: '',
      categories: [],
      complexity: QuestionComplexity.EASY,
    },
  })

  React.useEffect(() => {
    if (question) {
      reset(question)
    }
  }, [question, reset])

  const onSubmit = (data: QuestionFormData) => {
    onSave({ _id: question?._id, ...data } as Question)
  }

  const categoryOptions = Object.values(QuestionCategory).map(category => ({
    label: category,
    value: category,
  }))

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>{question?._id ? 'Edit Question' : 'Add Question'}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="title" className="text-right">
                Title
              </Label>
              <div className="col-span-3">
                <Controller
                  name="title"
                  control={control}
                  render={({ field }) => <Input {...field} />}
                />
                {errors.title && <p className="text-red-500 text-sm mt-1">{errors.title.message}</p>}
              </div>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="categories" className="text-right">
                Categories
              </Label>
              <div className="col-span-3">
                <Controller
                  name="categories"
                  control={control}
                  render={({ field }) => (
                    <MultiSelect
                      options={categoryOptions}
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                    />
                  )}
                />
                {errors.categories && <p className="text-red-500 text-sm mt-1">{errors.categories.message}</p>}
              </div>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="complexity" className="text-right">
                Complexity
              </Label>
              <div className="col-span-3">
                <Controller
                  name="complexity"
                  control={control}
                  render={({ field }) => (
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <SelectTrigger>
                        <SelectValue placeholder="Select complexity" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value={QuestionComplexity.EASY}>Easy</SelectItem>
                        <SelectItem value={QuestionComplexity.MEDIUM}>Medium</SelectItem>
                        <SelectItem value={QuestionComplexity.HARD}>Hard</SelectItem>
                      </SelectContent>
                    </Select>
                  )}
                />
                {errors.complexity && <p className="text-red-500 text-sm mt-1">{errors.complexity.message}</p>}
              </div>
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="description" className="text-right">
                Description
              </Label>
              <div className="col-span-3">
                <Controller
                  name="description"
                  control={control}
                  render={({ field }) => <Textarea {...field} className="min-h-[10em]" />}
                />
                {errors.description && <p className="text-red-500 text-sm mt-1">{errors.description.message}</p>}
              </div>
            </div>
          </div>
          <DialogFooter>
            <div className="w-full justify-between flex">
              <div>
                {question?._id && (
                  <Button
                    type="button"
                    variant="destructive"
                    size="sm"
                    onClick={onDelete}
                    className="bg-red-500 hover:bg-red-600 text-white"
                  >
                    <Trash2 className="h-4 w-4 mr-2" />
                    Delete
                  </Button>
                )}
              </div>
              <div className="flex gap-2">
                <Button type="button" variant="secondary" onClick={onClose}>
                  Cancel
                </Button>
                <Button type="submit">Save</Button>
              </div>
            </div>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
